### ISSUE TITLE
Wrong function parameter order in seq2seq

### ISSUE THREAD

**Issue by huikang** [PacktPublishing/Deep-Learning-with-TensorFlow-2-and-Keras#2]
https://github.com/PacktPublishing/Deep-Learning-with-TensorFlow-2-and-Keras/blob/b2639479d3e487005ba9098ed8eb37a1242226e8/Chapter%208/seq2seq_wo_attn.py#L47

The definition is

```python
class Encoder(tf.keras.Model):
    def __init__(self, vocab_size, num_timesteps, 
            embedding_dim, encoder_dim, **kwargs):
```
However, the encoder is create by

https://github.com/PacktPublishing/Deep-Learning-with-TensorFlow-2-and-Keras/blob/b2639479d3e487005ba9098ed8eb37a1242226e8/Chapter%208/seq2seq_wo_attn.py#L217

I think the correct order should be

```python
class Encoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, num_timesteps,
            encoder_dim, **kwargs):
```

**Comment by sujitpal** [comment]
Thank you, I have fixed the ordering in the class definition, to keep it in line with the ordering in the Decoder class definition.

**Comment by sujitpal** [comment]
Change applied via PR (https://github.com/PacktPublishing/Deep-Learning-with-TensorFlow-2-and-Keras/pull/6), awaiting merge.
