### ISSUE TITLE
Wrong in alice_text_generator.py

### ISSUE THREAD

**Issue by v3551G** [PacktPublishing/Deep-Learning-with-TensorFlow-2-and-Keras#4]
alice_text_generator.py:
 open(p, mode='r').read() -> open(p, mode='r', encoding='utf-8').read()

**Comment by sujitpal** [comment]
Thank you, for maximum portability, the encoding should be provided (especially for platforms whose default encoding is not utf-8. I have made the change and it should be available shortly in a PR.

**Comment by sujitpal** [comment]
Change applied via PR (https://github.com/PacktPublishing/Deep-Learning-with-TensorFlow-2-and-Keras/pull/6), awaiting merge.
