### ISSUE TITLE
Error at Chapter 7 Skipgram model (tf2_skipgram_model.py)

### ISSUE THREAD

**Issue by tjwodud04** [PacktPublishing/Deep-Learning-with-TensorFlow-2-and-Keras#5]
```
import tensorflow as tf

class SkipgramModel(tf.keras.Model):
    def __init__(self, vocab_sz, embed_sz, window_sz, **kwargs):
        super(SkipgramModel, self).__init__(**kwargs)
        self.word_model = tf.keras.Sequential([
            tf.keras.layers.Embedding(
                input_dim=vocab_sz,
                output_dim=embed_sz,
                embeddings_initializer="glorot_uniform",
                input_length=1
            ),
            tf.keras.layers.Reshape((embed_sz,))
        ])
        self.context_model = tf.keras.Sequential([
            tf.keras.layers.Embedding(
                input_dim=vocab_sz,
                output_dim=embed_sz,
                embeddings_initializer="glorot_uniform",
                input_length=1
            ),
            tf.keras.layers.Reshape((embed_sz,))
        ])
        self.merge = tf.keras.layers.Dot(axes=0)
        self.dense = tf.keras.layers.Dense(1,
                kernel_initializer="glorot_uniform",
                activation="sigmoid"
        )

    def call(self, input):
        word, context = input
        word_emb = self.word_model(word)
        context_emb = self.context_model(context)
        x = self.merge([word_emb, context_emb])
        x = self.dense(x)
        return x


VOCAB_SIZE = 5000
EMBED_SIZE = 300
WINDOW_SIZE = 1  # 3 word window, 1 on left, 1 on right

model = SkipgramModel(VOCAB_SIZE, EMBED_SIZE, WINDOW_SIZE)
model.build(input_shape=[(None, VOCAB_SIZE), (None, VOCAB_SIZE)])
model.compile(optimizer=tf.optimizers.Adam(),
    loss="categorical_crossentropy",
    metrics=["accuracy"])

model.summary()

# train the model here

# retrieve embeddings from trained model
word_model = model.layers[0]
word_emb_layer = word_model.layers[0]
emb_weights = None
for weight in word_emb_layer.weights:
    if weight.name == "embedding/embeddings:0":
        emb_weights = weight.numpy()
print(emb_weights, emb_weights.shape)
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-686126d6dd63> in <module>
     42 
     43 model = SkipgramModel(VOCAB_SIZE, EMBED_SIZE, WINDOW_SIZE)
---> 44 model.build(input_shape=[(None, VOCAB_SIZE), (None, VOCAB_SIZE)])
     45 model.compile(optimizer=tf.optimizers.Adam(),
     46     loss="categorical_crossentropy",

C:\Anaconda\envs\tensorflow2_py37\lib\site-packages\tensorflow_core\python\keras\engine\network.py in build(self, input_shape)
    680                            'method accepts an `inputs` argument.')
    681         try:
--> 682           self.call(x, **kwargs)
    683         except (errors.InvalidArgumentError, TypeError):
    684           raise ValueError('You cannot build your model by calling `build` '

<ipython-input-18-686126d6dd63> in call(self, input)
     32         word_emb = self.word_model(word)
     33         context_emb = self.context_model(context)
---> 34         x = self.merge([word_emb, context_emb])
     35         x = self.dense(x)
     36         return x

C:\Anaconda\envs\tensorflow2_py37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    776                     outputs = base_layer_utils.mark_as_return(outputs, acd)
    777                 else:
--> 778                   outputs = call_fn(cast_inputs, *args, **kwargs)
    779 
    780             except errors.OperatorNotAllowedInGraphError as e:

C:\Anaconda\envs\tensorflow2_py37\lib\site-packages\tensorflow_core\python\keras\layers\merge.py in call(self, inputs)
    179         return y
    180     else:
--> 181       return self._merge_function(inputs)
    182 
    183   @tf_utils.shape_type_conversion

C:\Anaconda\envs\tensorflow2_py37\lib\site-packages\tensorflow_core\python\keras\layers\merge.py in _merge_function(self, inputs)
    533       x1 = nn.l2_normalize(x1, axis=axes[0])
    534       x2 = nn.l2_normalize(x2, axis=axes[1])
--> 535     output = K.batch_dot(x1, x2, axes)
    536     return output
    537 

C:\Anaconda\envs\tensorflow2_py37\lib\site-packages\tensorflow_core\python\keras\backend.py in batch_dot(x, y, axes)
   1785   # sanity checks
   1786   if 0 in axes:
-> 1787     raise ValueError('Cannot perform batch_dot over axis 0. '
   1788                      'If your inputs are not batched, '
   1789                      'add a dummy batch dimension to your '

ValueError: Cannot perform batch_dot over axis 0. If your inputs are not batched, add a dummy batch dimension to your inputs using K.expand_dims(x, 0)

**Comment by sujitpal** [comment]
Thank you for catching the error. I have fixed the code to use a shared embedding layer and to use the Flatten layer instead of Reshape. It should be available in a PR shortly.

**Comment by sujitpal** [comment]
Change applied via PR (https://github.com/PacktPublishing/Deep-Learning-with-TensorFlow-2-and-Keras/pull/6), awaiting merge.
